openapi: 3.0.3
info:
  title: User Service API
  description: API для управления пользовательскими интерфейсами и токенами.
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local server
tags:
  - name: User Interface
    description: Endpoints для управления пользовательским интерфейсом.
  - name: Token Utils
    description: Endpoints для работы с токенами.

paths:
  /v1/api/ui/balance:
    get:
      tags:
        - User Interface
      summary: Получение баланса пользователя или бизнеса
      description: Возвращает баланс в зависимости от роли (`user` или `business`).
      responses:
        "200":
          description: Успешный ответ с балансом.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceInfo"
        "401":
          description: Ошибка, неверный токен доступа.
      parameters:
        - name: access_token
          in: cookie
          description: Access-токен пользователя/бизнеса в куки.
          required: true
          schema:
            type: string

  /v1/api/auth-utils/refresh:
    get:
      tags:
        - Token Utils
      summary: Обновление access-токена с помощью refresh-токена
      description: Создает новый access-токен на основе корректного refresh-токена.
      responses:
        "200":
          description: Успешное обновление токена.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenInfo"
        "401":
          description: Ошибка, неверный refresh-токен.
      parameters:
        - name: refresh_token
          in: cookie
          description: Refresh-токен в виде cookie.
          required: true
          schema:
            type: string

components:
  schemas:
    BalanceInfo:
      type: object
      properties:
        balance:
          type: integer
          description: Баланс пользователя или бизнеса.
          example: 1500
    TokenInfo:
      type: object
      properties:
        access_token:
          type: string
          description: Новый access-токен.
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
