name: CI for FastAPI (dev branch)

on:
  push:
    branches:
      - dev # Запуск на ветке dev

env:
  POOL_SIZE: 500
  MAX_OVERFLOW: 100
  SERVER_PORT: 8000
  IP_ADDRESS: 127.0.0.1
  JWT_SECRET_KEY: SECRET_KEY
  DB_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Проверка API
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Настройка кеша pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('marketplace/backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Клонирование приложение с dev ветки
        run: |
          git clone https://github.com/laughteryache/marketplace.git -b dev

      - name: Создание таблиц
        run: |
          cd marketplace/backend/sql
          psql postgresql://postgres:postgres@localhost:5432/postgres -f tables.sql

      - name: Установка зависимостей
        run: |
          cd marketplace/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск приложения
        run: |
          cd marketplace/backend/src
          python main.py &  # Запускаем в фоне
          sleep 2  # Ждем, пока сервер поднимется

      - name: Запуск тестов
        run: |
          cd marketplace/backend
          pytest --disable-warnings --maxfail=1

      - name: Остановка сервера
        run: |
          pkill -f "python main.py" || true  # Останавливаем сервер
